// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetAppsData():Promise<any>;

export function LoadImage(arg1:string):Promise<string>;

export function OpenFile():Promise<any>;

export function Startup(arg1:context.Context):Promise<void>;
