// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppsData() {
  return window['go']['fileService']['FileService']['GetAppsData']();
}

export function LaunchApps() {
  return window['go']['fileService']['FileService']['LaunchApps']();
}

export function LoadImage(arg1) {
  return window['go']['fileService']['FileService']['LoadImage'](arg1);
}

export function OpenFile() {
  return window['go']['fileService']['FileService']['OpenFile']();
}

export function RemoveApp(arg1) {
  return window['go']['fileService']['FileService']['RemoveApp'](arg1);
}

export function Startup(arg1) {
  return window['go']['fileService']['FileService']['Startup'](arg1);
}
